from pyspark.sql.types import StructType, StructField, IntegerType, DoubleType, StringType, DecimalType

def get_schema(schema_name):
    """
    Function to return the appropriate schema based on the input argument.
    """
    schemas = {
        'SIH': {'UF_ZI': StringType(),
                'ANO_CMPT': StringType(),
                'MES_CMPT': StringType(),
                'ESPEC': StringType(),
                'CGC_HOSP': StringType(),
                'N_AIH': StringType(),
                'IDENT': 'char(1)',
                'CEP': StringType(),
                'MUNIC_RES': StringType(),
                'NASC': StringType(),
                'SEXO': 'char(1)',
                'UTI_MES_IN': StringType(),
                'UTI_MES_AN': StringType(),
                'UTI_MES_AL': StringType(),
                'UTI_MES_TO': 'numeric(3)',
                'MARCA_UTI': StringType(),
                'UTI_INT_IN': StringType(),
                'UTI_INT_AN': StringType(),
                'UTI_INT_AL': StringType(),
                'UTI_INT_TO': 'numeric(3)',
                'DIAR_ACOM': 'numeric(3)',
                'QT_DIARIAS': 'numeric(3)',
                'PROC_SOLIC': StringType(),
                'PROC_REA': StringType(),
                'VAL_SH': 'numeric(13,2)',
                'VAL_SP': 'numeric(13,2)',
                'VAL_SADT': StringType(),
                'VAL_RN': StringType(),
                'VAL_ACOMP': StringType(),
                'VAL_ORTP': StringType(),
                'VAL_SANGUE': StringType(),
                'VAL_SADTSR': StringType(),
                'VAL_TRANSP': StringType(),
                'VAL_OBSANG': StringType(),
                'VAL_PED1AC': StringType(),
                'VAL_TOT': 'numeric(14,2)',
                'VAL_UTI': 'numeric(8,2)',
                'US_TOT': 'numeric(8,2)',
                'DT_INTER': 'char(8)',
                'DT_SAIDA': 'char(8)',
                'DIAG_PRINC': StringType(),
                'DIAG_SECUN': StringType(),
                'COBRANCA': StringType(),
                'NATUREZA': StringType(),
                'NAT_JUR': StringType(),
                'GESTAO': 'char(1)',
                'RUBRICA': StringType(),
                'IND_VDRL': 'char(1)',
                'MUNIC_MOV': StringType(),
                'COD_IDADE': 'char(1)',
                'IDADE': 'numeric(2)',
                'DIAS_PERM': 'numeric(5)',
                'MORTE': 'numeric(1)',
                'NACIONAL': StringType(),
                'NUM_PROC': StringType(),
                'CAR_INT': StringType(),
                'TOT_PT_SP': StringType(),
                'CPF_AUT': StringType(),
                'HOMONIMO': 'char(1)',
                'NUM_FILHOS': 'numeric(2)',
                'INSTRU': 'char(1)',
                'CID_NOTIF': StringType(),
                'CONTRACEP1': StringType(),
                'CONTRACEP2': StringType(),
                'GESTRISCO': 'char(1)',
                'INSC_PN': StringType(),
                'SEQ_AIH5': StringType(),
                'CBOR': StringType(),
                'CNAER': StringType(),
                'VINCPREV': 'char(1)',
                'GESTOR_COD': StringType(),
                'GESTOR_TP': 'char(1)',
                'GESTOR_CPF': StringType(),
                'GESTOR_DT': StringType(),
                'CNES': StringType(),
                'CNPJ_MANT': StringType(),
                'INFEHOSP': 'char(1)',
                'CID_ASSO': StringType(),
                'CID_MORTE': StringType(),
                'COMPLEX': StringType(),
                'FINANC': StringType(),
                'FAEC_TP': StringType(),
                'REGCT': StringType(),
                'RACA_COR': StringType(),
                'ETNIA': StringType(),
                'SEQUENCIA': 'numeric(9)',
                'REMESSA': StringType(),
                'AUD_JUST': StringType(),
                'SIS_JUST': StringType(),
                'VAL_SH_FED': 'numeric(8,2)',
                'VAL_SP_FED': 'numeric(8,2)',
                'VAL_SH_GES': 'numeric(8,2)',
                'VAL_SP_GES': 'numeric(8,2)',
                'VAL_UCI': 'numeric(8,2)',
                'MARCA_UCI': StringType(),
                'DIAGSEC1': StringType(),
                'DIAGSEC2': StringType(),
                'DIAGSEC3': StringType(),
                'DIAGSEC4': StringType(),
                'DIAGSEC5': StringType(),
                'DIAGSEC6': StringType(),
                'DIAGSEC7': StringType(),
                'DIAGSEC8': StringType(),
                'DIAGSEC9': StringType(),
                'TPDISEC1': 'char(1)',
                'TPDISEC2': 'char(1)',
                'TPDISEC3': 'char(1)',
                'TPDISEC4': 'char(1)',
                'TPDISEC5': 'char(1)',
                'TPDISEC6': 'char(1)',
                'TPDISEC7': 'char(1)',
                'TPDISEC8': 'char(1)',
                'TPDISEC9': 'char(1)'},
        'SIA': {'PA_CODUNI': StringType(),
                'PA_GESTAO': StringType(),
                'PA_CONDIC': StringType(),
                'PA_UFMUN': StringType(),
                'PA_REGCT': StringType(),
                'PA_INCOUT': StringType(),
                'PA_INCURG': StringType(),
                'PA_TPUPS': StringType(),
                'PA_TIPPRE': StringType(),
                'PA_MN_IND': 'char(1)',
                'PA_CNPJCPF': StringType(),
                'PA_CNPJMNT': StringType(),
                'PA_CNP_CC': StringType(),
                'PA_DATPR': StringType(),
                'PA_DATREF': StringType(),
                'PA_PROCID': StringType(),
                'PA_TPFIN': StringType(),
                'PA_SUBFIN': StringType(),
                'PA_NIVCPL': 'char(1)',
                'PA_DOCORIG': 'char(1)',
                'PA_AUTORIZ': StringType(),
                'PA_CNSMED': StringType(),
                'PA_CBOCOD': StringType(),
                'PA_MOTSAI': StringType(),
                'PA_CIDPRI': StringType(),
                'PA_CIDSEC': StringType(),
                'PA_CIDCAS': StringType(),
                'PA_IDADE': StringType(),
                'PA_SEXO': 'char(1)',
                'PA_RACACOR': StringType(),
                'PA_MUNPCT': StringType(),
                'PA_QTDPRO': 'numeric(8)',
                'PA_QTDAPR': 'numeric(8)',
                'PA_CODOCO': 'char(1)',
                'PA_INDICA': 'char(1)',
                'PA_VALPRO': 'numeric(20,2)',
                'PA_VALAPR': 'numeric(20,2)',
                'PA_UFDIF': 'char(1)',
                'PA_MNDIF': 'char(1)',
                'PA_DIF_VAL': 'numeric(20,2)',
                'NU_VPA_TOT': 'numeric(20,2)',
                'NU_PA_TOT': 'numeric(20,2)'}
    }

    if schema_name not in schemas:
        raise ValueError(f"Schema '{schema_name}' is not defined.")
    
    #expected schema
    schemaWrite = schemas[schema_name]
    #expected schema using stringtype as default
    schemaRead = StructType([StructField(key, StringType(), True) for key in schemaWrite.keys()])
    
    return schemaWrite, schemaRead